export enum EnumBatiment_TypeBatiment {
  NA = 'NA',
  EQUIPEMENT_SPORTIF = 'EQUIPEMENT_SPORTIF',
  LOGEMENT_COLLECTIF = 'LOGEMENT_COLLECTIF',
  RESTAURATION = 'RESTAURATION',
  ENSEIGNEMENT = 'ENSEIGNEMENT',
  HOPITAL = 'HOPITAL',
  AUTRE = 'AUTRE',
  BUREAUX = 'BUREAUX'
}

export enum EnumBatiment_TypeStructure {
  NA = 'NA',
  BETON = 'BETON',
  BOIS = 'BOIS',
  MIXTE = 'MIXTE'
}

export enum EnumBatiment_TypeTravaux {
  CHAUFFAGE_VENTILATION_CLIMATISATION = 'CHAUFFAGE_VENTILATION_CLIMATISATION',
  CLOISONNEMENT_DOUBLAGE = 'CLOISONNEMENT_DOUBLAGE',
  FACADES_ET_MENUISERIES = 'FACADES_ET_MENUISERIES',
  SUPERSTRUCTURES_MACONNERIE = 'SUPERSTRUCTURES_MAÇONNERIE',
  SANITAIRES = 'SANITAIRES',
  VOIRIE = 'VOIRIE',
  COUVERTURE_ETANCHEITE = 'COUVERTURE_ETANCHÉITÉ',
  ELECTRICITE = 'ELECTRICITE',
  REVETEMENTS_DE_SOLS_ET_MURS = 'REVETEMENTS_DE_SOLS_ET_MURS',
  FONDATIONS_INFRASTRUCTURES = 'FONDATIONS_INFRASTRUCTURES',
  COMMUNICATION = 'COMMUNICATION'
}

export enum EnumBatiment_TypeMobilier {
  ARMOIRE= 'ARMOIRE',
  CANAPE = 'CANAPE',
  CHAISES_BOIS = 'CHAISES_BOIS',
  CHAISES_BOIS_TEXTILE = 'CHAISES_BOIS_TEXTILE',
  CHAISES_PLASTIQUES = 'CHAISES_PLASTIQUES',
  CHAISES_MOYENNE = 'CHAISES_MOYENNE',
  LIT = 'LIT',
  TABLE = 'TABLE',
  ASPIRATEUR_CLASSIQUE = 'ASPIRATEUR_CLASSIQUE',
  ASPIRATEUR_TRAINEAU_PRO = 'ASPIRATEUR_TRAINEAU_PRO',
  CLIMATISEUR_MOBILE = 'CLIMATISEUR_MOBILE',
  CONGELATEUR_ARMOR = 'CONGELATEUR_ARMOR',
  CONGELATEUR_COFFRE = 'CONGELATEUR_COFFRE',
  LAVELINGE_7KG = 'LAVELINGE_7KG',
  SECHE_LINGE_6KG = 'SECHE_LINGE_6KG',
  LAVE_VAISSELLE = 'LAVE_VAISSELLE',
  MACHINE_A_CAFE_EXPRESSO = 'MACHINE_A_CAFE_EXPRESSO',
  MACHINE_A_CAFE_FILTRE = 'MACHINE_A_CAFE_FILTRE',
  MACHINE_A_CAFE_DOSETTES = 'MACHINE_A_CAFE_DOSETTES',
  MACHINE_A_CAFE_MOYENNE = 'MACHINE_A_CAFE_MOYENNE',
  BOUILLOIRE = 'BOUILLOIRE',
  MICRO_ONDES = 'MICRO_ONDES',
  PLAQUES_DE_CUISSON = 'PLAQUES_DE_CUISSON',
  RADIATEUR_ELECTRIQUE = 'RADIATEUR_ELECTRIQUE',
  REFRIGERATEUR = 'REFRIGERATEUR',
  AUTRE_MOBILIER_EN_EUROS = 'AUTRE_MOBILIER_EN_EUROS',
  AUTRE_MOBILIER_EN_TONNES = 'AUTRE_MOBILIER_EN_TONNES'
}
