export enum PARKING_VOIRIE_TYPE {
  PARKING = 'PARKING',
  VOIRIE = 'VOIRIE',
  NA = 'NA'
}

export enum PARKING_VOIRIE_TYPE_STRUCTURE {
  BETON_ARME = 'BETON_ARME',
  BITUME = 'BITUME',
  SEMI_RIGIDE = 'SEMI_RIGIDE'
}
