export enum TypeMachineEnum {
  ARMOIRE = "ARMOIRE",
  DRV = "DRV",
  EAU_GLACEE_MOINS_50KW = "EAU_GLACEE_MOINS_50KW",
  EAU_GLACEE_PLUS_50KW = "EAU_GLACEE_PLUS_50KW",
  INCONNU = "INCONNU",
  NA = "NA"
}
